name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compilar EXE
        run: |
          pyinstaller --onefile --windowed --clean --name MediaFireDownloader main.py

      - name: Guardar EXE
        uses: actions/upload-artifact@v4
        with:
          name: MediaFireDownloader-Windows
          path: dist/MediaFireDownloader.exe
